name: radix_tree
version: 2.0.0
description: Map based Dart implementation of the Radix Tree data structure.
repository: https://github.com/ykmnkmi/radix-tree.dart
funding:
  - https://www.buymeacoffee.com/ykmnkmi

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
